version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: springcurse_mysql
    environment:
      MYSQL_DATABASE: springcurse
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
